version: '3.8'

services:
  python-api:
    build: ./python-api
    ports:
      - "5000:5000"
    container_name: log-analyser-api

  node-client:
    build: ./node-client
    depends_on:
      - python-api
    container_name: log-analyser-client